---
title: "box-cox-with-PCA"
output: html_document
date: "2023-08-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the required libraries
library(tidyverse)
library(caret)
library(MASS)
library(car)


```

```{r}
# Load the dataset
data <- read.csv("pca_data_250.csv")  # Update with the actual CSV file name

# Display the structure of the loaded data
str(data)

```

```{r}
# Load the dplyr package for data manipulation
library(dplyr)

# Normalize each feature to the range [0, 1]
normalized_data <- data %>%
  mutate(across(starts_with("Feature"), ~ (.-min(.)) / (max(.) - min(.))))

# Display the first few rows of the normalized data
head(normalized_data)


```

```{r}
col_name <- NULL;
for (i in 1:250) {
  
  col_name <-  paste0(col_name,"Feature_", i,"+")
  #data[, col_name] <- boxcox(data[, paste0("Feature_", i)], lambda = NULL)$x
}
cat(col_name)
```

```{r}
model_2  = lm(pred_prob ~ Feature_1+Feature_2+Feature_3+Feature_4+Feature_5+Feature_6+Feature_7+Feature_8+Feature_9+Feature_10+Feature_11+Feature_12+Feature_13+Feature_14+Feature_15+Feature_16+Feature_17+Feature_18+Feature_19+Feature_20+Feature_21+Feature_22+Feature_23+Feature_24+Feature_25+Feature_26+Feature_27+Feature_28+Feature_29+Feature_30+Feature_31+Feature_32+Feature_33+Feature_34+Feature_35+Feature_36+Feature_37+Feature_38+Feature_39+Feature_40+Feature_41+Feature_42+Feature_43+Feature_44+Feature_45+Feature_46+Feature_47+Feature_48+Feature_49+Feature_50+Feature_51+Feature_52+Feature_53+Feature_54+Feature_55+Feature_56+Feature_57+Feature_58+Feature_59+Feature_60+Feature_61+Feature_62+Feature_63+Feature_64+Feature_65+Feature_66+Feature_67+Feature_68+Feature_69+Feature_70+Feature_71+Feature_72+Feature_73+Feature_74+Feature_75+Feature_76+Feature_77+Feature_78+Feature_79+Feature_80+Feature_81+Feature_82+Feature_83+Feature_84+Feature_85+Feature_86+Feature_87+Feature_88+Feature_89+Feature_90+Feature_91+Feature_92+Feature_93+Feature_94+Feature_95+Feature_96+Feature_97+Feature_98+Feature_99+Feature_100+Feature_101+Feature_102+Feature_103+Feature_104+Feature_105+Feature_106+Feature_107+Feature_108+Feature_109+Feature_110+Feature_111+Feature_112+Feature_113+Feature_114+Feature_115+Feature_116+Feature_117+Feature_118+Feature_119+Feature_120+Feature_121+Feature_122+Feature_123+Feature_124+Feature_125+Feature_126+Feature_127+Feature_128+Feature_129+Feature_130+Feature_131+Feature_132+Feature_133+Feature_134+Feature_135+Feature_136+Feature_137+Feature_138+Feature_139+Feature_140+Feature_141+Feature_142+Feature_143+Feature_144+Feature_145+Feature_146+Feature_147+Feature_148+Feature_149+Feature_150+Feature_151+Feature_152+Feature_153+Feature_154+Feature_155+Feature_156+Feature_157+Feature_158+Feature_159+Feature_160+Feature_161+Feature_162+Feature_163+Feature_164+Feature_165+Feature_166+Feature_167+Feature_168+Feature_169+Feature_170+Feature_171+Feature_172+Feature_173+Feature_174+Feature_175+Feature_176+Feature_177+Feature_178+Feature_179+Feature_180+Feature_181+Feature_182+Feature_183+Feature_184+Feature_185+Feature_186+Feature_187+Feature_188+Feature_189+Feature_190+Feature_191+Feature_192+Feature_193+Feature_194+Feature_195+Feature_196+Feature_197+Feature_198+Feature_199+Feature_200+Feature_201+Feature_202+Feature_203+Feature_204+Feature_205+Feature_206+Feature_207+Feature_208+Feature_209+Feature_210+Feature_211+Feature_212+Feature_213+Feature_214+Feature_215+Feature_216+Feature_217+Feature_218+Feature_219+Feature_220+Feature_221+Feature_222+Feature_223+Feature_224+Feature_225+Feature_226+Feature_227+Feature_228+Feature_229+Feature_230+Feature_231+Feature_232+Feature_233+Feature_234+Feature_235+Feature_236+Feature_237+Feature_238+Feature_239+Feature_240+Feature_241+Feature_242+Feature_243+Feature_244+Feature_245+Feature_246+Feature_247+Feature_248+Feature_249+Feature_250, data = normalized_data)
summary(model_2)
```

```{r}

plot(model_2)
```

```{r}

residuals <- residuals(model_2)

# Create the AV plot
avPlots(model_2)

# Create the CR plot
crPlots(model_2)

```

```{r}
# Apply Box-Cox transformation to the target variable (response) if needed
# For example, if you have a response variable named 'y', you can transform it like this:
# data$y_transformed <- boxcox(data$y, lambda = NULL)
# Uncomment and modify the above line based on your data

# Apply Box-Cox transformation to the features
# Assuming the transformed features are named 'Feature_1_transformed', ..., 'Feature_10_transformed'

boxcox(data[, paste0("Feature_1")], lambda = NULL)
for (i in 1:10) {
  boxcox(data[, paste0("Feature_", i)], lambda = NULL)
  #col_name <- paste0("Feature_", i, "_transformed")
  #data[, col_name] <- boxcox(data[, paste0("Feature_", i)], lambda = NULL)$x
}

# Define the list of transformed feature names
transformed_feature_names <- paste0("Feature_", 1:10, "_transformed")  # Adjust the range as needed

# Construct the formula for MLR
formula <- reformulate(transformed_feature_names, response = "y")

# Perform Multiple Linear Regression (MLR) using the transformed features
model <- lm(formula, data = data)

# Display the summary of the MLR model
summary(model)


```
